// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mswsgplzwsbdgcggtova.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zd3NncGx6d3NiZGdjZ2d0b3ZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MzczOTcsImV4cCI6MjA2NDAxMzM5N30.wAg7wA0NasdehVQVCHJRQRovMQTZrnEnjqEQ-jQ_GGA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);